/****** Object:  Table [dbo].[roles]    Script Date: 10/10/2020 11:04:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[roles](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [nchar](50) NOT NULL,
	[ROLE_DESCRIPTION] [nchar](500) NOT NULL,
	[CREATED_DATE] [timestamp] NOT NULL,
	[CREATED_BY] [int] NOT NULL,
	[UPDATED_DATE] [time](7) NULL,
	[UPDATED_BY] [int] NULL,
	[ACTIVE_FLAG] [nchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[roles] ADD  CONSTRAINT [DF_roles_ACTIVE_FLAG]  DEFAULT (N'n') FOR [ACTIVE_FLAG]
GO

ALTER TABLE [dbo].[roles]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[usersDB] ([USER_ID])
GO

ALTER TABLE [dbo].[roles]  WITH CHECK ADD FOREIGN KEY([UPDATED_BY])
REFERENCES [dbo].[usersDB] ([USER_ID])
GO


